
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://mycrudserver.database.windows.net:1433;database=crudDB;user=adminlogin@mycrudserver;password=Qwer123#;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminlogin
    password: Qwer123#

