server:
  port: 9090
  servlet:
    context-path: /recruitment

spring:
  application:
    name: RECRUITMENT-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://mycrudserver.database.windows.net:1433;database=crudDB;user=adminlogin@mycrudserver;password=Qwer123#;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminlogin
    password: Qwer123#


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
